version: '1.0'
services:

  # api:
  #   container_name: api_v1
  #   image: node:20
  #   tty: true
  #   build: ./api        
  #   ports:
  #    - 5080:5080
  #   depends_on:
  #    - mysql 
  #   volumes:
  #    - .:/opt/src
  #   working_dir: /opt/src/api
  #   env_file:
  #    - .env 
  #   restart: always  

  # ui:
  #   container_name: ui_v1
  #   image: node:20
  #   tty: true
  #   build: ./ui
  #   ports:
  #    - "8080:8080"
  #   volumes:
  #    - .:/opt/src 
  #   working_dir: /opt/src/ui
  #   env_file:
  #     - .env  
  #   restart: always    

  mysql:
    container_name: mysql_v1
    build: ./mysql
    ports:
      - 3306:3306
    env_file:
     - .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}   
    restart: always   
