/***CREATING ALL TABLES*/
CREATE TABLE TABLE1 (
  Id   INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  Name1    VARCHAR(40)                    NULL,
);

/* INSERT DATA */
INSERT INTO EMPLOYEE (Name1)
VALUES ('test 1');


